### ISSUE TITLE
inbody 수치 

### ISSUE THREAD

**Issue by gimbab2002** [sst7050/Health_Kitchen_Project#10]
사용자로부터 인바디 수치를 입력받아 json파일에 유저정보와 함께 저장하려 합니다. 
그리고 입력받은 입력받은 인바디를 일정 기준을 보고 정상체형을 위해 체중을 늘려야하는지, 빼야하는지 유지해야하는지에 대한 항목 또한 json 파일에 입력하려 합니다. 
다른의견이나 인바디 체중 증량 감량 유지 기준 코멘트 해주세요

**Comment by sst7050** [comment]
인바디 수치의 왼쪽 부분은 '분석 결과' 이고, 오른쪽 부분은 해당 결과를 바탕으로 내린 '분석 평가' 입니다. 따라서 어차피 전문가의 견해를 통해 체중조절 가이던스가 우리에게 필요한 형태로 나타나 있기 때문에, 우리는 사용자에게 분석 평가값을 받아서 기준값을 정하면 될 것같아요. 지금부터 말씀드릴 내용은 '분석 평가'를 기준으로 드리는 말씀이니 참고해 주세요.

인바디 점수의 기준은 80점입니다. 근육과 지방비율에 따라 해당 인원의 점수가 80점 미만이면 체지방을 줄이고 근육량을 증가시켜야 합니다.

영양평가 항목도 있는데, 해당 인원의 단백질, 무기질, 체지방량이 어느 수준인지 평가 해 줍니다.

핵심적으로 체중 조절 항목이 있는데요, 그곳에서 해당 인원에게 이상적인 적정 체중량을 지정해 주고, 그것을 위해 지방을 조절해야 할지 근육을 조절해야 할 지에 대해서 상세하게 정보가 나옵니다. 마른 비만의 경우 적정 체중임에도 근육을 +kg 늘리고 지방을 -kg 줄이라고 표시됩니다. 우리는 여기서 체지방의 감소만 지향할 것이 아니라 근육량의 유지도 신경써야 한다는 것을 알 수 있습니다.

신체균형평가는 부위별 근육량의 불균형을 평가해 줍니다.

부위별 체지방 분석을 해 주는데 이 항목을 통해 어떤 근력 운동 루틴 위주로 추천해 주어야 할 지 짐작 할 수 있습니다.

인바디 데이터에서 연구항목은 내장지방, 골무기질량 등의 정보가 나와 있는데 이러한 항목들은 전문적인 지식을 요구하므로 우선은 고려하지 않는 것이 적절해 보입니다. 

현재로써 기능에 적합한 정보들만 추려내어 결론적으로 말씀 드리자면 제 생각에는 
사용자로부터 인바디 점수값, 체중조절 항목값을 입력받아 해당 점수가 80점 미만이고 (and) 체중조절 중 특히 지방 조절(-)(혹은 지방조절(-) and 근육조절(+))이 필요한 경우에는 '지방 감량', '지방 감량 및 근육 증량', 
인바디 점수가 80점 미만이고 (and)  체중조절 중 지방조절(+) (혹은 지방조절(+) and 근육조절 (+))이 필요한 경우에는 '지방 증량','지방 증량 및 근육 증량', 
인바디 점수가 80점 이상이고 (and) 체중조절 항목에 조절해야 할 값이 없는 경우에는 '유지' 값을 출력해야 할 것 같다고 판단했습니다. 기존의 단순 감량, 증량, 유지라는 세 가지 출력값보다 항목을 세분화 하는 것이 정보와 매칭될 것 같아서요.

**Comment by gimbab2002** [comment]
점수 구하는 알고리즘이 따로 있나요? @sst7050

**Comment by gimbab2002** [comment]
Pull request #19 
GUI_basic_info.py가 아닌 GUI_main.py에서 파일이 실행되도록 변경하였습니다. 그리고 GUI_main.py의 클래스를 분리해야 한다고 느껴서 모든 클래스를 GUI_MainScreen.py 파일에 넣었습니다. 이제 GUI_main.py는 실행 코드를 명확하게 볼 수 있기 때문에 훨씬 더 좋아 보일 것입니다.

**Comment by gimbab2002** [comment]
Pr#20 에서는
위에서 말한 대로, 인바디 점수가 80점 이상이면 status는 '유지' 인바디 점수가 80점 이하이고, 
지방조절항목이 0보다 작으면 '지방감량' 
지방조절항목이 0보다 작고 근육조절항목이 0보다 크면 '지방감량 및 근육 증량' 
지방조절항목이 0보다 크면 '지방 증량' 
지방조절항목이 0보다 크고 근육조절항목이 0보다 크면 '지방감량 및 근육 증량'
으로 사용자의 status를 업데이트함. 사용자가 모든 정보를 입력한 후에 바로 분석하여 json파일에 추가하여 저장하고, 바로 status를 출력하도록 바꿈.
