### ISSUE TITLE
프로그램 실행 관련

### ISSUE THREAD

**Issue by gimbab2002** [sst7050/Health_Kitchen_Project#11]
현재 프로그램 실행은 GUI_basic_info.py 파일에서 실행해야되는데 이걸 GUI_Main.py 에서 실행되도록 바꾸는 게 어떨까요?

**Comment by sst7050** [comment]
네, 그러면 그렇게 바꾸죠. 어차피 결과적으로 GUI 관련 파일은 다 메인에서 실행되도록 해야 합니다.

**Comment by cOcOa-aa** [comment]
그게 더 좋아 보여요. GUI_Main 에서 실행했을 때 userinfo가 없는 경우 GUI_basic_info가 실행되도록 하면 될 것 같습니다.

**Comment by sst7050** [comment]
브랜치 이름은 무조건 Feature 로 시작해야 합니다.

**Comment by gimbab2002** [comment]
GUI_basic_info.py가 아닌 GUI_main.py에서 파일이 실행되도록 변경되었습니다. 그리고 GUI_main.py의 클래스를 분리해야 한다고 느꼈기 때문에 모든 클래스를 GUI_MainScreen.py에 넣었습니다. 이제 GUI_main.py는 실행 코드를 명확하게 볼 수 있기 때문에 훨씬 더 좋아 보일 것입니다.
