### ISSUE TITLE
브랜치 관련하여 질문

### ISSUE THREAD

**Issue by sst7050** [sst7050/Health_Kitchen_Project#12]
기존에 작성했던 파일들이 메인 브랜치로 이미 merge 되었는데, 지금 해당 파일들 중 GUI_basic_info.py 파일 내용을 다시 수정해야 할 일이 생겼습니다. 이런 경우 그냥 해당 파일만 수정해서 커밋 하고 다시 푸시 하면 되는 건가요? 아니면 새로운 브랜치를 다시 만들어서 다시 해당 파일의 수정본을 커밋 푸시 해야 하는 건가요? 이미 merge된 기존의 브랜치 파일을 수정하는 것이 가능한지 여쭤보고 싶습니다.

**Comment by gimbab2002** [comment]
브랜치 만들어서 commit 후 merge하는게 좋아보입니다

**Comment by sst7050** [comment]
Feature_GUI_Fix 로 브랜치 새로 만들어서 MR 하는 방향으로 가겠습니다.
