### ISSUE TITLE
GUI 유저 정보 입력 값 관련

### ISSUE THREAD

**Issue by sst7050** [sst7050/Health_Kitchen_Project#13]
현 시점 GUI에 입력하는 항목은 성별, 키, 몸무게, 나이 수치입니다. Discussion을 통해 개선된 항목은 나이, 성별, 인바디 점수, 적정 체중, 체중조절, 지방조절, 근육조절 수치입니다. 이 항목에 대해서 건의사항이나 요청사항 있으면 자유롭게 작성 해 주세요.

**Comment by cOcOa-aa** [comment]
그정도 입력받으면 될 것 같습니다😊
