### ISSUE TITLE
제공할 음식 선정

### ISSUE THREAD

**Issue by cOcOa-aa** [sst7050/Health_Kitchen_Project#14]
치킨		교촌치킨 반반 오리지날(2만)
편의점	CU 모바일 상품권 2만원권(2만)
피자		파파존스 2만원 할인권(2만)
		반올림피자R +  콜라500ml(1.9만)
햄버거	맥날, 맘터, KFC등 2만원권(2만)
커피		스타벅스 피스타치오 크림 콜드 브루 T + 라이트 핑크 자몽 피지오 T + 치킨 & 머쉬룸 멜팅 치즈 샌드위치(1.9만)
빵		뚜레쥬르 2만원권(2만)
베라		쿼터 아이스크림(1.8만)

일단 이런식으로 정해봤는데 편의점, 햄버거, 빵같은 카테고리는 교환권으로 주는 게 제일 깔끔한 것 같아요.
2만원 선에 최대한 맞춰서 골랐습니다. 더 나은 제품이나 생각 있으시면 말해주세요.😁

**Comment by sst7050** [comment]
제 생각에는 좋은 것 같습니다!

**Comment by cOcOa-aa** [comment]
다른 의견이 없어 위에 작성한 음식으로 확정하겠습니다!
