### ISSUE TITLE
보상 변경에 따른 음식 변경안 + 재료

### ISSUE THREAD

**Issue by cOcOa-aa** [sst7050/Health_Kitchen_Project#23]
기존에 기프티콘의 형태로 제공하려던 보상을 변경함에 따라 선정하였던 음식들도 변경하여야 할 필요가 있을 것 같아 작성하게 되었습니다. 읽어보시고 의견 있으시면 코멘트 부탁드립니다, 추가로 음식 당 4개의 재료도 간단하게  적었습니다.

스테이크 - 고기, 야채, 기름, 소스(소금후추등등)
파스타 - 파스타면, 소스, 야채, 고기
치킨 - 닭, 튀김가루, 기름, 소스
피자 - 도우, 소스, 고기, 야채
햄버거 - 빵, 패티, 야채, 소스
필라프 - 쌀, 고기, 야채, 소스
스튜 - 고기, 토마토캔?, 야채, 소스

**Comment by sst7050** [comment]
혹시 해당 보상들의 대략적인 값어치는 비슷한 수준일까요? 예를 들어 스테이크와 햄버거 가격 차이가 심하다면 보상 기준을 좀 차등화 해야 하지 않을까 싶습니다.

**Comment by gimbab2002** [comment]
해당사항 모두 반영되었으므로 이슈 닫겠습니다.
