### ISSUE TITLE
Feature_GUI_status 브랜치 파일 오류 관련

### ISSUE THREAD

**Issue by sst7050** [sst7050/Health_Kitchen_Project#25]
현재 해당 브랜치를 pull 하여 파일을 실행하면 def get_exercise_recommendation(self, status) 함수 부분이 정상적으로 실행되지 않습니다. 해당 버그에 대해 해결 가능하신 분 계실까요?

**Comment by sst7050** [comment]
어느정도 버그를 수정하였으나 여전히 지방, 근육량이 표준인 사람에 대해서 정상 작동하지 않습니다. 이 부분에 대해서 fix 의견 요청드립니다.

**Comment by gimbab2002** [comment]
인바디 점수가 80점 이상일 때에는 status 값을 0으로 주고 bmi에 따라서 운동추천을 추천해주는 함수 또는 메서드를 하나 더 만들어야 할 것 같습니다.  if문으로 inbody 점수가 80점 이상일 때 status값을 0으로 주고 bmi값에 따라 status에 가중치를 주어 그 값들을 ifelse문으로 통제하면 좋을 것 같습니다.

**Comment by sst7050** [comment]
의견 감사합니다. 한번 적용 해볼게요.
