### ISSUE TITLE
메인화면 이미지

### ISSUE THREAD

**Issue by cOcOa-aa** [sst7050/Health_Kitchen_Project#27]
![KakaoTalk_20240520_195353306](https://github.com/sst7050/Health_Kitchen_Project/assets/85469644/8abfaef7-4575-4b33-8b27-13b9c507a174)

5월 10일 회의 때 정한 의견대로 메인 화면에 쓰일 화면을 만들었습니다. 크게 3가지 기능을 넣을 걸 예상하고 만들었습니다.
1) 냉장고 - 냉장고 기능 버튼
2) 모니터 - 운동 입력 기능 버튼
3) 음식 - 내 정보 기능 버튼

**Comment by gimbab2002** [comment]
보내주신 사진 바탕으로 메인화면 만들어보았습니다. 이슈 닫겠습니다.
