### ISSUE TITLE
GUI_MainScreen.py 파일의 독립

### ISSUE THREAD

**Issue by gimbab2002** [sst7050/Health_Kitchen_Project#28]
기존 GUI_MainScreen은 Class와 Method만 정의되어 있어서 GUI_Main.py에서 import를 해 메인화면 창을 생성했었습니다. 하지만 GUI_MainScreen.py 독립적으로 실행되도록 설정하여, 유지보수에 더욱 도움이 될 것입니다. 그에 맞춰 GUI_Main.py파일에서도 os.system()으로 메인화면 실행하여 더욱 코드는 깔끔해질 것입니다.ㅣ

**Comment by cOcOa-aa** [comment]
좋은 것 같습니다,

**Comment by sst7050** [comment]
좋은 아이디어 입니다. 실행 상 문제만 발생하지 않는다면 앞으로도 이런 식으로 방향을 잡는것이 맞는 것 같아요.

**Comment by gimbab2002** [comment]
모두 확인하셨으므로 이슈 닫습니다.
