### ISSUE TITLE
메인화면 구성 

### ISSUE THREAD

**Issue by gimbab2002** [sst7050/Health_Kitchen_Project#29]
기존에 구상한 회의내용에 맞추어서 메인화면을 구성해보았습니다. 
![image](https://github.com/sst7050/Health_Kitchen_Project/assets/69901143/937168b4-af47-4cb4-aa9f-6fd38d553696)
모습은 다음과 같습니다. 현재 많이 부족하기 때문에 많은 의견 부탁드립니다.

**Comment by cOcOa-aa** [comment]
냉장고 버튼 부분을 이미지로 변경하고 손잡이부분까지 버튼으로 포함하면 좋을 것 같습니다!
