### ISSUE TITLE
메인화면(또는 다른 화면)의 글꼴 처리 

### ISSUE THREAD

**Issue by gimbab2002** [sst7050/Health_Kitchen_Project#31]
작업을 하면서 든 생각은, 글꼴을 포함시키면 좋을 것 같다는 생각이 들었습니다. 현재 글꼴은 테마와 잘 안어울리는 것 같아 이슈 남깁니다. 저는 배달의 민족 글씨체를 포함시키것이 어떠할까 싶습니다. 
![image](https://github.com/sst7050/Health_Kitchen_Project/assets/69901143/d6d90bca-85aa-46b3-aef7-c1042d5e856f)
위 글꼴 말고도 좋은 글꼴이 있으면 추천 부탁드립니다.

**Comment by cOcOa-aa** [comment]
배민 글씨체 좋은 것 같습니다. 저는 "도현" 또는 한나는 열한살" 글씨체가 괜찮은 것 같아요!

**Comment by sst7050** [comment]
저도 동감입니다. 아무래도 글씨체는 식별하기 쉬우며 친근한 글씨체가 좋은 것 같아요. "한나는 열한살" 추천드립니다!

**Comment by cOcOa-aa** [comment]
의견이 많은 "한나는 열한살" 글씨체로 진행하겠습니다.

**Comment by cOcOa-aa** [comment]
변경 완료하여 이슈 닫습니다.
