### ISSUE TITLE
CustomTkinter 사용 의견

### ISSUE THREAD

**Issue by gimbab2002** [sst7050/Health_Kitchen_Project#34]
우리 프로그램이 더 예쁘게 보이기 위한 방법을 좀 찾아봤는데, github에 custom Tkinter라고 누군가가 올려놓은게 있더라고요
https://github.com/TomSchimansky/CustomTkinter
보고 이거로 적용하면 어떨 것 같은지 의견 주세요
설치도 간단해요 pip3 install customtkinter 로 설치 가능합니다.
다른 분이 만든 커스텀tkinter 있으면 또 올려주세요 제일 나은걸로 합시다.

**Comment by sst7050** [comment]
더 나은 대안을 찾기 전 까지는 우선 저걸로 진행하는 것이 제일 최선책일 것 같아요.

**Comment by cOcOa-aa** [comment]
Custom Tkinter 설치하려면 기존에 만들었던 것들을 모두 뒤집어야 하는 경우가 생겨 Custon Tkinter는 사용하지 않는 걸로 하였습니다.
