### ISSUE TITLE
int 값 변환 관련 문의

### ISSUE THREAD

**Issue by sst7050** [sst7050/Health_Kitchen_Project#35]
get exercise recommendation 함수 return 값 중 정수 부분 int 값으로 변환하는 건에 대해서, 문장에 있는 숫자만 int형으로 변경하면 되는 것일까요?

**Comment by gimbab2002** [comment]
운동 목표 시간(유산소, 무산소)을 따로 빼야 진척도 상황 체크시에 편하게 코드를 짤 수 있을 것 같습니다.

**Comment by cOcOa-aa** [comment]
동균이 말대로 해야 운동량 계산할 때 편할 것 같습니다.

**Comment by sst7050** [comment]
그런데 우선 함수 값 내부에서는 서로 구분 할 수 없을 것 같아요..
