### ISSUE TITLE
json 파일 읽기, 쓰기

### ISSUE THREAD

**Issue by cOcOa-aa** [sst7050/Health_Kitchen_Project#36]
운동진행상황을 만들며 json파일을 읽거나 쓸 때 encoding='utf-8' 를 사용하면 json 파일에 한글이 유니코드가 아닌 한글로 저장되는 것을 확인하였습니다. 한글로 저장되는 것이 개발하는 과정에 더 편할 것 같아 작성된 코드들에 encoding='utf-8' 를 모두 추가하였습니다. 확인해주시고 앞으로도 사용해주시면 감사할 것 같습니다. 이에 의견 있으시면 편하게 달아주세요.

**Comment by gimbab2002** [comment]
utf-8로 바꾸는 것 확인했습니다.
