### ISSUE TITLE
음식과 재료 관련하여

### ISSUE THREAD

**Issue by gimbab2002** [sst7050/Health_Kitchen_Project#38]
commit 6a93c38915863d8f7d4cb7a2d6a3a97ff9f2ccd9
에 보면 프로그레스 바와 재료 이미지 추가했다고 커밋 메시지에 되어있는데 아직 음식사진과 재료는 추가가 안 된 것 같아서요

**Comment by cOcOa-aa** [comment]
아 죄송합니다. 빠른 시일 내에 재료 이미지 추가 및 변경 하겠습니다.

**Comment by cOcOa-aa** [comment]
음식 이미지 변경 및 재료 이미지 추가 완료하여 이슈 닫도록 하겠습니다.
