### ISSUE TITLE
json파일의 utf-8 인코딩 적용 

### ISSUE THREAD

**Issue by gimbab2002** [sst7050/Health_Kitchen_Project#39]
작업 도중 인코딩 관련하여 궁금증이 생겨서 올립니다. 사진과 같이 적용되는데, 찾아보니 
데이터를 한글로 저장하고 싶다면, 저장시에 ensure_ascii=False 옵션을 넣어주면 된다.
라고 검색결과가 나오네요.
https://hayjo.tistory.com/75 참고하시길 바랍니다.

![image](https://github.com/sst7050/Health_Kitchen_Project/assets/69901143/13d446d5-9d6f-44f3-881f-c74eafa4602b)

**Comment by cOcOa-aa** [comment]
그렇군요. 감사합니다. 이것도 파일 읽기 및 쓰기 시에 포함하면 될까요?

**Comment by gimbab2002** [comment]
읽기는 상관없고 쓰기 할때 ensure_ascii=False 옵션 넣으면 좋을 것 같네요
