### ISSUE TITLE
Feature_GUI_status 브랜치 merge 관련

### ISSUE THREAD

**Issue by gimbab2002** [sst7050/Health_Kitchen_Project#40]
해당 브랜치가 main브랜치에 비해 4개의 커밋은 앞서고, 13개의 커밋이 뒤쳐지는데, 같은 파일이 수정된 경우, 메인에 merge 하면은 conflict가 발생할 수도 있을 것 같습니다.
아마 배운대로 main을 먼저 Feature_GUI_status 브랜치에 merge 해보고 conflict 발생 시, 현재 main 브랜치에 맞추어서 코드 내용을 조금씩은 수정해야 할 필요가 있을 수도 있을 것 같습니다. 바로 merge가 되면 다행이지만, 그렇지 않을 경우 도움이 필요하시다면 언제든지 연락 주세요.

**Comment by sst7050** [comment]
그럼 먼저  Feature_GUI_status  브랜치로 체크 아웃 한 다음에 main 브랜치를 merge 해 보라는 말씀이신 거죠?

**Comment by gimbab2002** [comment]
![image](https://github.com/sst7050/Health_Kitchen_Project/assets/69901143/53d5cef5-7bd0-4bd5-85c8-b88785f33112)
사진 참고하시면 좋을 것 같습니다!

**Comment by gimbab2002** [comment]
해당 브랜치 merge 되었으므로 issue 닫습니다.
