### ISSUE TITLE
Feature_time_limit 브랜치 작업내용

### ISSUE THREAD

**Issue by gimbab2002** [sst7050/Health_Kitchen_Project#41]
1. 음식선택을 했을 때, 현재 시간에 일주일을 더하여 시간제한(목표날짜)을 json파일에 저장함
2. 이후 MainScreen.py가 실행될 때, 그리고 Progress bar 화면에서 '유산소 추가' 또는 '무산소 추가' 버튼을 눌렀을 때, 현재 시간을 읽어 json파일의 시간과 비교하여 음식을 다시 선택하도록 변경. 

시간확인을 더 해야하는 부분이 있다면 comment 달아주세요.

**Comment by cOcOa-aa** [comment]
#54 작업 완료하여 이슈 닫습니다.
