### ISSUE TITLE
메인화면에서 '사용자 정보' 버튼을 클릭하면

### ISSUE THREAD

**Issue by sst7050** [sst7050/Health_Kitchen_Project#42]
메인화면에서 '사용자 정보' 버튼을 클릭하면 운동 추천 정보를 포함한 사용자 정보가 출력되어야 하는데, 그렇게 되지 않습니다.. 혹시 이 부분 fix 가능하신 분 계실까요??

**Comment by gimbab2002** [comment]
일단 GUI_Status 브랜치 병합하고 진행하죠
