### ISSUE TITLE
GUI_Main.py 파일 병합 관련 이슈_2

### ISSUE THREAD

**Issue by sst7050** [sst7050/Health_Kitchen_Project#49]
지금 GUI_Main.py에 Feature_GUI_status merge 관련 기존 conflict 요소를 모두 제거한 뒤 다시 Pull request를 요청했지만, 이번에는 userInfo.py 파일에서 conflict 요소가 발견되었습니다. 문제는 제가 기존에 하던대로 conflict 해결 절차를 터미널에 입력했지만 이미 merged 되었다는 식의 메세지만 출력 될 뿐입니다. 혹시 이것에 대해 아이디어 있으실까요?

**Comment by gimbab2002** [comment]
깃헙 홈페이지 웹에디터에서 해결하면 될 것 같습니다.

**Comment by gimbab2002** [comment]
제가할게요
