### ISSUE TITLE
Feature_time_limit브랜치 main으로 merge 후 프로그램 실행 시 발생하는 오류

### ISSUE THREAD

**Issue by gimbab2002** [sst7050/Health_Kitchen_Project#53]
메인브랜치로 merge 후에 프로그램을 다시 실행하여봤더니 json파일을 읽는 부분에서 error가 발생하여 수정하겠습니다. 기존에 있던 브랜치에서 하나 더 커밋하여 merge하는 식으로 진행하겠습니다.

**Comment by cOcOa-aa** [comment]
수고하셨습니다. Merge 완료하여 이슈 닫겠습니다.
