### ISSUE TITLE
냉장고 기능 관련 의견

### ISSUE THREAD

**Issue by gimbab2002** [sst7050/Health_Kitchen_Project#58]
냉장고에 단순히 재료만 보관하는 것이 아닌, 지금까지 만든 음식들이 나타나면 더 좋을 것 같습니다.
냉장고 배경이미지도 삽입가능하다면 넣었으면 좋겠습니다.

의견 더 있으시면 comment 남겨주세요

**Comment by cOcOa-aa** [comment]
냉장고 배경이미지는 넣으려고 생각중이었습니다, 지금까지 만든 음식을 포함하는 것은 좋은 의견인 것 같습니다.

**Comment by cOcOa-aa** [comment]
지금까지 만든 음식을 볼 수 있는 화면을 따로 구성 완료하였습니다. 이슈 닫습니다.
