### ISSUE TITLE
GUI_Sel_food 관련

### ISSUE THREAD

**Issue by cOcOa-aa** [sst7050/Health_Kitchen_Project#60]
현재 Sel_food에 음식마다 duration과 price가 책정되어 있는데, 보상같은 부분이 바뀌면서 이 부분이 필요가 없어지거나 수정이 필요해졌다고 생각합니다. 어떻게 하면 좋을지 의견 주시면 감사하겠습니다.

**Comment by gimbab2002** [comment]
네 코드 간결화시키는건 좋다고 생각합니다. 필요 없는 데이터는 없애는게 좋아 보이네요

**Comment by cOcOa-aa** [comment]
#72 작업 완료되어서 이슈 닫습니다.
