### ISSUE TITLE
GUI_Main.py 코드 오류 관련

### ISSUE THREAD

**Issue by sst7050** [sst7050/Health_Kitchen_Project#61]
subprocess.run('GUI_basic_info.py') 해당 명령어가 계속 작동되지 않기 때문에 해당 부분을 주석 처리하고 대신에 import GUI_basic_info 명령어를 입력했더니 정상적으로 해당 명령어가 작동되었습니다. 이렇게 수정한 뒤 계속 작업하는것에 대해서 여러분들의 의견은 어떠한지 묻고 싶습니다.
<img width="968" alt="스크린샷 2024-05-29 오후 4 09 57" src="https://github.com/sst7050/Health_Kitchen_Project/assets/153179706/2945958c-0684-44c1-8033-d162deea2be8">

**Comment by gimbab2002** [comment]
mac os 환경에서 실행 시 말씀하시는 건가요?

**Comment by gimbab2002** [comment]
현재 윈도우에서는 위 코드 실행시 아예 프로그램 작동이 안됩니다.

**Comment by sst7050** [comment]
그냥 제가 컴퓨터실에서 작업하는것이 가장 합리적인 것 같습니다. 해당 부분은 걱정 안하셔도 됩니다!
