### ISSUE TITLE
랭크 시스템 이미지

### ISSUE THREAD

**Issue by cOcOa-aa** [sst7050/Health_Kitchen_Project#64]
랭크 시스템 이미지를, 뒤집개로 하면 괜찮을 것 같습니다! 랭크가 올라가면 색을 변경하거나 뒤집개의 수를 늘리는 등의 식으로 차별점을 주면 좋을 것 같아 의견 적습니다.

**Comment by sst7050** [comment]
그런데 랭크 이름중에 요리왕 비룡과 고든 램지가 있는데, 그 랭크 역시 뒤집개로 하는게 좋을까요?

**Comment by cOcOa-aa** [comment]
음.. 그건 편하신대로 하시면 될 것 같습니다. 의견이 생각나서 말씀드린거라 꼭 뒤집개로 안하시고 다른걸로 하셔도 괜찮습니다!
