### ISSUE TITLE
만든 음식 버튼 이미지

### ISSUE THREAD

**Issue by cOcOa-aa** [sst7050/Health_Kitchen_Project#68]
새로운 버튼을 어떤 이미지로 하는 게 괜찮을지 의견을 구하고 싶어 이슈 올립니다.
1. 트로피
2. 빵모자(요리사 모자)
제가 생각해본 건 이정도 있는데 다른 좋은 아이디어 있으시면 말해주시면 감사하겠습니다.

**Comment by gimbab2002** [comment]
오븐모양도 괜찮을 것 같습니다!

**Comment by cOcOa-aa** [comment]
기존에는 만든 음식 창에 랭크 이미지를 함께 넣을 예정이었으나, 회의를 통해 랭크 이미지를 메인화면에서 바로 보이도록 변경하여 만든 음식은 집기류 사진으로 하게 되었습니다.
#69 작업 완료하여 이슈 닫습니다.
