### ISSUE TITLE
만든 음식 창 출력 관련

### ISSUE THREAD

**Issue by cOcOa-aa** [sst7050/Health_Kitchen_Project#70]
현재 만든 코드는, 만든 음식이 없을 때 아래 사진처럼 "만든 음식이 없습니다."라는 메세지를 적은 창이 뜨게 되어있습니다.
![스크린샷 2024-06-03 125201](https://github.com/sst7050/Health_Kitchen_Project/assets/85469644/6f99496e-00ad-453d-8f69-41d988d66d53)
그런데 만든 음식이 없을 때는 오류 메세지 창만 출력해주는 것이 더 괜찮을 것 같다는 생각이 들어서 의견을 듣고 싶어 이슈 남깁니다.

**Comment by sst7050** [comment]
제 생각에는 현재 버전이 더 괜찮아 보입니다. 실제로 동류의 프로그램이나 어플리케이션을 구동하다 보면 비슷한 상황에서 오류 메세지를 출력하기 보다는 저런 식으로 창을 띄워준 뒤 거기에 글을 출력하는 경우가 더 일반적이기 때문입니다.

**Comment by gimbab2002** [comment]
깔끔한거는 messagebox.showinfo로 알림창만 띄우는 것이 더 깔끔할 것 같아요 현재는 폰트도 폰트고, 가운데 정렬이 안되어서...

**Comment by cOcOa-aa** [comment]
알림창만 띄우자는 의견이 많아 그렇게 수정하였습니다.
