### ISSUE TITLE
README 파일 관련

### ISSUE THREAD

**Issue by sst7050** [sst7050/Health_Kitchen_Project#71]
저희의 프로그램 방향성이 완전히 바뀌었기 때문에, README 파일 역시 수정이 불가피하다고 생각합니다. 자유로운 의견 부탁드립니다!

**Comment by gimbab2002** [comment]
가상의 음식 재료를 받아서 가상의 음식을 만들어 랭크가 올라간다는 내용이 들어갔으면 좋겠습니다. 그리고 음식 만들 때 걸리는 시간도 한달이라고 명시했으면 좋겠습니다. 돌발퀴즈부분은 삭제하는 것이 맞겠네요
