### ISSUE TITLE
unittest 파일 할당

### ISSUE THREAD

**Issue by gimbab2002** [sst7050/Health_Kitchen_Project#80]
총 9개의 파일을 테스트해야 합니다. 인당 3개씩 하면 딱 될 것 같습니다. 테스트할 파일 comment 해주세요

**Comment by cOcOa-aa** [comment]
GUI_MainScreen.py
GUI_Progress_info.py
GUI_Rank.py
하겠습니다.

**Comment by gimbab2002** [comment]
GUI_Sel_Food.py
GUI_Refrigerator.py
user_info.py

**Comment by sst7050** [comment]
GUI_Main.py
GUI_Made_Food.py
GUI_basic_info.py
