### ISSUE TITLE
추후 프레젠테이션 관련 Discussion

### ISSUE THREAD

**Issue by sst7050** [sst7050/Health_Kitchen_Project#84]
저희가 다음주 금요일, 6월 14일에 있을 프레젠테이션 관련해서 각자 역할을 분담하려 합니다. 발표 역할은 메인 발표자 한 명, 보조 발표자 한 명, ppt 준비자 한 명 이렇게 총 세 명으로 이루어 질 것입니다. 각자 자신이 원하는 역할을 여기에 적어 주세요.

**Comment by sst7050** [comment]
저는 메인 발표자를 하고 싶습니다.

**Comment by gimbab2002** [comment]
저는 중간고사 발표때처럼 ppt 준비 하겠습니다!
