### ISSUE TITLE
unittest 1차결과

### ISSUE THREAD

**Issue by gimbab2002** [sst7050/Health_Kitchen_Project#85]
모두 고생하셨습니다. 현재 9개 파일들의 1차 unittest 진행상황 공유드리겠습니다.
![image](https://github.com/sst7050/Health_Kitchen_Project/assets/69901143/6408a94e-514d-468e-a009-b4524edda7cc)
현재 평균 퍼센트는 80%이고, 일단 9개의 파일 모두 unittest가 되었다는 부분이 매우 만족스럽네요.

**Comment by sst7050** [comment]
추후애 더 분발해야 할 부분은 test 파일이 참조하는 원본의 coverage 퍼센트를 향상시키는 작업이 될 것입니다.

**Comment by gimbab2002** [comment]
확인했습니다. 모든 파일이 80%이상이 되었으므로 이슈 닫습니다~
