### ISSUE TITLE
unittest의 퍼센트 높이기

### ISSUE THREAD

**Issue by gimbab2002** [sst7050/Health_Kitchen_Project#86]
현재 test파일들의 coverage는 90% 이상으로 높은 편이지만 그에 반에 원본 파일들의 coverage는 매우 낮습니다. 문제는 unittest에 반영되지 않은 함수들이 있을 것입니다. 그 함수들을 unittest에 추가해 주세요. 현재 9개의 파일들 모두 unittest 작동을 하니, 조금씩만 수정하면 가능할 것입니다. 본인이 맡았던 부분의 coverage를 높이도록 노력하면 좋겠네요.

**Comment by sst7050** [comment]
GUI_basic_info 원본과 GUI_Main 원본의 경우 각각 96%, 80%로 상당히 높은 편이지만, GUI_Made_Food의 경우 coverage가 49%로 매우 낮은 관계로 해당 파일을 수정하는 데 주력하도록 하겠습니다.

**Comment by gimbab2002** [comment]
모두 완료되었습니다! 이슈 닫습니다
