### ISSUE TITLE
사용자 정보 입력 받는 부분에 대해

### ISSUE THREAD

**Issue by cOcOa-aa** [sst7050/Health_Kitchen_Project#9]
현재 GUI_basic_info 에서 입력을 받을 때, 성별, 키, 몸무게, 나이 순서로 하나씩 입력 받고 있습니다.
이걸 한 화면에서 한 번에 입력받는 걸로 바꾸는 건 어떤지 의견을 듣고 싶습니다😊

**Comment by sst7050** [comment]
한 화면에 받는 것이 더 좋을 것 같습니다. 성별 같이 명확한 선택값을 가진 선택지는 선다형으로 하고, 나머지 요소는 직접 입력형으로 하는 기존의 방식은 그대로 유지하죠! 그리고 입력 질문은 인바디 참조 방식에 따라 수정되어야 할 것 같습니다.
